version: '3'

services:
  django: &django
    image: infrascielo/upload
    container_name: upload_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    expose:
      - "8000"
    command: /start

  nginx:
      image: nginx:latest
      container_name: upload_nginx
      volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
          - ./nginx/logs:/var/log/nginx/
      ports:
          - "80:80"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: upload_production_postgres
    container_name: upload_production_postgres
    volumes:
      - ../scms_data/data_prod:/var/lib/postgresql/data:Z
      - ../scms_data/data_prod_backup:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6
    container_name: upload_production_redis

  celeryworker:
    <<: *django
    image: upload_production_celeryworker
    container_name: upload_production_celeryworker
    command: /start-celeryworker
    ports: []

  celerybeat:
    <<: *django
    image: upload_production_celerybeat
    container_name: upload_production_celerybeat
    command: /start-celerybeat
    ports: []

  flower:
    <<: *django
    image: upload_production_flower
    container_name: upload_production_flower
    command: /start-flowe
    ports: []